### ISSUE TITLE
items = { error: 'resource not found' }

### ISSUE THREAD

**Issue by feed0** [bootdotdev/fcc-learn-http-assets#4]
Is the API down or something?

Note: I am using node on my local pc.

**Comment by feed0** [comment]
Seems there is new code at [boot.dev learn http](https://www.boot.dev/lessons/09ed0562-5760-4a78-919a-0233fa9b3227) using a new api url that ends in **/issues** instead of **/items** 

`'https://api.boot.dev/v1/courses_rest_api/learn-http/issues'`

**Comment by bdcdo** [comment]
I think this issue should be reopened and the code should be updated.
